### ISSUE TITLE
Write up for the home page

### ISSUE THREAD

**Issue by rennys66** [mocaspike150/mocaspike150.github.io#2]
At the Museum of Chinese in America (MOCA), a national cultural institution that tells the untold stories in the making of America through the lens of the Chinese immigrant experience, visitors are greeted with the Chinese proverb: “A journey of a thousand miles begins with a single step.” It is our way of honoring the pioneering spirit of not only Chinese immigrants but all immigrants who sacrificed and dared to take the first step that blazed a path for future generations in America. 

With 2019 being the 150th anniversary of the historic moment when a golden spike was driven into the ground at Promontory Summit in Utah to mark the completion of the Transcontinental Railroad, the Museum has launched the MOCA Spike 150 initiative to not only honor the resilience, grit, and ingenuity symbolized by the thousands of Chinese laborers responsible for this milestone but of all immigrants in America. This nine-month initiative will feature a series of fundraising events, the biggest of which will be the TCS NYC Marathon on November 3 where we are inviting runners to follow in the footsteps of this country's first pioneers and make history by supporting MOCA. 

#18

**Comment by ontouchstart** [comment]
https://mocaspike150.github.io/
