### ISSUE TITLE
Write a document (Chris personal issue)

### ISSUE THREAD

**Issue by chang1812** [mocaspike150/mocaspike150.github.io#21]
Find the usage for each folder

**Comment by ontouchstart** [comment]
Information about Jekyll

- https://jekyllrb.com/
- https://jekyllrb.com/docs/
- https://jekyllrb.com/docs/step-by-step/01-setup/

You can study and add your links and notes here (editing it) or add more comments.

**Comment by ontouchstart** [comment]
BTW, you do not need to install Jekyll on your computer, GitHub already did for you in this repo. Study the document below and understand how it works.

https://help.github.com/en/categories/github-pages-basics

**Comment by ontouchstart** [comment]
You can write anything in this folder to learn Jekyll

https://github.com/mocaspike150/mocaspike150.github.io/tree/master/sandbox

**Comment by ontouchstart** [comment]
I made a root link to sandbox so it is easy to go back to the source code:

https://mocaspike150.github.io/sandbox/

To see how it is done, see commit https://github.com/mocaspike150/mocaspike150.github.io/commit/4518c4631557a3d8c9858774b83a613397e70f28
