### ISSUE TITLE
create a blog section

### ISSUE THREAD

**Issue by rennys66** [mocaspike150/mocaspike150.github.io#26]
First test: 
Earlier this month on March 6th, MOCA supporter Johnson Shen climbed to the summit of Mount Aconcagua, which at 6961 m is the highest mountain outside of Asia.  Shen scaled the mountain in 12 hours and 25 minutes and had to compete with wind speeds of up to 96 kph.  In the picture Shen is sporting a MOCA t-shirt in support of our MOCA Spike 150 initiative.  

Renny, once I get a higher resolution image from him (his internet signal is bad still right now), let's put it on our spike website.
![img_0618](https://user-images.githubusercontent.com/46349226/54041782-927bd680-4196-11e9-8bd1-1725f7ca260c.jpg)

**Comment by ontouchstart** [comment]
Closed due to #28
