### ISSUE TITLE
Ambassador list

### ISSUE THREAD

**Issue by rennys66** [mocaspike150/mocaspike150.github.io#29]
How easy to put the list of ambassdor from Crowdrise to this page?
It should be a combination list from https://www.crowdrise.com/o/en/campaign/moca-spike-150 and  https://www.crowdrise.com/o/en/campaign/moca-spike-150-ambassadors

#17

**Comment by ontouchstart** [comment]
The teams are here:

- https://www.crowdrise.com/o/en/campaignTeams/961029/0/6/0
- https://www.crowdrise.com/o/en/campaignTeams/963816/0/6/0

**Comment by ontouchstart** [comment]
Test here:

https://mocaspike150.github.io/wp/ambassadors.html

**Comment by ontouchstart** [comment]
Yes we can have that page load live data as well. It will be in the next test.

**Comment by ontouchstart** [comment]
Live data need a customer API that I will write later.

**Comment by ontouchstart** [comment]
API test 

http://moca-spike-150.appspot.com/crowdrise/
