### ISSUE TITLE
MOCA Font upload

### ISSUE THREAD

**Issue by rennys66** [mocaspike150/mocaspike150.github.io#3]
Need to try how to use MOCA font into css

**Comment by ontouchstart** [comment]
- https://mocaspike150.github.io/assets/font-test.html
- https://github.com/mocaspike150/mocaspike150.github.io/blob/master/assets/font-test.html
- https://github.com/mocaspike150/mocaspike150.github.io/tree/master/assets/

**Comment by ontouchstart** [comment]
https://mocaspike150.github.io/assets/fonts/demo.html

**Comment by ontouchstart** [comment]
https://mocaspike150.github.io/assets/fonts/stylesheet.css

**Comment by ontouchstart** [comment]
- https://mocaspike150.github.io/assets/fonts/EdmundsburySansRegular-Regular/demo.html
- https://mocaspike150.github.io/assets/fonts/Sifonn-Pro/demo.html

**Comment by ontouchstart** [comment]
check font on live site: https://mocaspike150.github.io/
