### ISSUE TITLE
Footer development

### ISSUE THREAD

**Issue by rennys66** [mocaspike150/mocaspike150.github.io#6]
Test footer in live site at

https://mocaspike150.github.io

#17

**Comment by rennys66** [comment]
Please move the icons to replace the description

**Comment by rennys66** [comment]
Cecilia's comments
left column text change to Navy; Insert MOCA logo; Museum of Chinese in America in Verlag bold, rest of location in Verlag Book. Social media icons: change to white, 55 px, no boarder. Maybe start as a separate column so it fits mobile view?

![](https://user-images.githubusercontent.com/48104795/53976086-4bc5a800-40d4-11e9-9503-b7d5fbf3b99c.jpg)

**Comment by rennys66** [comment]
Everything is good except the social icon color to white and the size adjustment

**Comment by ontouchstart** [comment]
Closed due to #28
