### ISSUE TITLE
Can't get the pig run link work

### ISSUE THREAD

**Issue by rennys66** [mocaspike150/mocaspike150.github.io#8]
https://mocaspike150.github.io/about/moca-spike-150/

#18

**Comment by ontouchstart** [comment]
Pigrun link fixed. But these pages are lot listed on nav

- https://mocaspike150.github.io/about/moca-spike-150/
- https://mocaspike150.github.io/events/2019/02/10/kick-off-run

**Comment by rennys66** [comment]
Thanks. That's fine, we keep those on the deep link for now.

Renny
